In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
df = pd.DataFrame(data.data, columns = data.feature_names)

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df['target'] = data.target

In [10]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
df['target'].unique()

array([0, 1, 2])

In [12]:
#EDA

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [14]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [15]:
# Model Building

In [16]:
X = df.drop('target', axis = 1)
y = df['target']

In [17]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [18]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=42)

In [21]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]

In [22]:
X_test

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
31                 5.4               3.4                1.5               0.4
64                 5.6               2.9                3.6               1.3
141                6.9               3.1                5.1               2.3
68                 6.2               2.2                4.5               1.5
82                 5.8               2.7                3.9               1.2
110                6.5               3.2                5.1               2.0
12                 4.8               3.0                1.4               0.1
36                 5.5               3.5                1.3               0.2
9                  4.9               3.1                1.5               0.1
19                 5.1               3.8                1.5               0.3
56                 6.3               3.3                4.7               1.6
104                6.5               3.0                5.8               2.2
69                 5.6               2.5                3.9               1.1
55                 5.7               2.8                4.5               1.3
132                6.4               2.8                5.6               2.2
29                 4.7               3.2                1.6               0.2
127                6.1               3.0                4.9               1.8
26                 5.0               3.4                1.6               0.4
128                6.4               2.8                5.6               2.1
131                7.9               3.8                6.4               2.0
145                6.7               3.0                5.2               2.3
108                6.7               2.5                5.8               1.8
143                6.8               3.2                5.9               2.3
45                 4.8               3.0                1.4               0.3
30                 4.8               3.1                1.6               0.2

In [23]:
y_train

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: target, Length: 120, dtype: int64

In [24]:
y_test

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: target, dtype: int64

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
clf = LogisticRegression(max_iter=150)
clf

LogisticRegression(max_iter=150)

In [27]:
clf.fit(X_train, y_train)

LogisticRegression(max_iter=150)

In [28]:
y_pred = clf.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

### Evaluation Metrics for Logistic Regression

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [31]:
print(confusion_matrix(y_test, y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [32]:
print(accuracy_score(y_test, y_pred))

1.0


### Cross Validation

In [33]:
from sklearn.model_selection import KFold

In [34]:
cv = KFold(n_splits=5)
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [35]:
clf

LogisticRegression(max_iter=150)

In [36]:
from sklearn.model_selection import cross_val_score

In [37]:
scores=cross_val_score(clf, X_train, y_train, scoring = 'accuracy', cv = cv)

In [38]:
np.mean(scores)

0.9666666666666666

### Hyperparameter Tuning

In [39]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [40]:
parameters = {"penalty":('l1','l2','elastic_net'),'C':[1,5,8,10]}


In [41]:
parameters

{'penalty': ('l1', 'l2', 'elastic_net'), 'C': [1, 5, 8, 10]}

In [42]:
clf = LogisticRegression()
clf

LogisticRegression()

In [43]:
clf = GridSearchCV(clf, param_grid=parameters, cv=5)
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 5, 8, 10],
                         'penalty': ('l1', 'l2', 'elastic_net')})

In [44]:
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 5, 8, 10],
                         'penalty': ('l1', 'l2', 'elastic_net')})

In [45]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [46]:
clf.best_score_

0.9666666666666666

In [47]:
clf_new=LogisticRegression(C=1,penalty='l2')
clf_new.fit(X_train,y_train)

LogisticRegression(C=1)

In [48]:
y_pred = clf_new.predict(X_test)

In [49]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [50]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print("Confusion", confusion_matrix(y_test,y_pred))
print("Accuracy : ", accuracy_score(y_test,y_pred))
print("classification_report", classification_report(y_test,y_pred))

Confusion [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy :  1.0
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [51]:
clf.predict_proba(X_test)

array([[3.78540536e-03, 8.27210040e-01, 1.69004555e-01],
       [9.46727170e-01, 5.32726301e-02, 1.99986472e-07],
       [8.72385695e-09, 1.55691544e-03, 9.98443076e-01],
       [6.43448555e-03, 7.92126722e-01, 2.01438792e-01],
       [1.44095507e-03, 7.74344685e-01, 2.24214360e-01],
       [9.55768196e-01, 4.42316271e-02, 1.76849604e-07],
       [7.76122937e-02, 9.08082088e-01, 1.43056180e-02],
       [1.61401764e-04, 1.55690377e-01, 8.44148221e-01],
       [2.20736359e-03, 7.62834324e-01, 2.34958312e-01],
       [2.83154099e-02, 9.45798684e-01, 2.58859062e-02],
       [4.39679077e-04, 2.43281228e-01, 7.56279093e-01],
       [9.68307934e-01, 3.16919881e-02, 7.80649368e-08],
       [9.72933932e-01, 2.70660346e-02, 3.33361450e-08],
       [9.62096919e-01, 3.79029701e-02, 1.10921543e-07],
       [9.79272619e-01, 2.07273164e-02, 6.47441610e-08],
       [4.54276495e-03, 7.12605191e-01, 2.82852044e-01],
       [7.22631012e-06, 2.42037672e-02, 9.75789006e-01],
       [2.73294494e-02, 9.47693

## Randomised Search CV

In [65]:
from sklearn.model_selection import RandomizedSearchCV

In [66]:
random_clf = LogisticRegression()

In [67]:
random_clf = RandomizedSearchCV(random_clf, param_distributions = parameters, cv=5, n_iter=15)

In [68]:
random_clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=15,
                   param_distributions={'C': [1, 5, 8, 10],
                                        'penalty': ('l1', 'l2', 'elastic_net')})

In [69]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=15,
                   param_distributions={'C': [1, 5, 8, 10],
                                        'penalty': ('l1', 'l2', 'elastic_net')})

In [70]:
random_clf.best_params_

{'penalty': 'l2', 'C': 1}

## Multiclass Classification

In [71]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [72]:
# Define Dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_classes=3, random_state=1)

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [77]:
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [78]:
model.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [79]:
y_pred = model.predict(X_test)

In [80]:
y_pred

array([1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 2, 2, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 1, 0, 0, 2, 0,
       2, 0, 2, 1, 0, 0, 1, 1, 0, 2, 0, 2, 1, 0, 2, 1, 0, 1, 2, 2, 0, 2,
       1, 1, 1, 0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 1, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 2, 1,
       2, 1, 1, 0, 1, 2, 2, 0, 0, 0, 2, 1, 1, 0, 2, 0, 2, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2,
       2, 1, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0,
       1, 2, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 2, 0, 1, 0, 1,
       0, 1])

In [81]:
model.predict_proba(X_test)

array([[0.12483378, 0.7723409 , 0.10282533],
       [0.53142631, 0.12602548, 0.34254821],
       [0.02878653, 0.6650178 , 0.30619567],
       [0.5644855 , 0.09031569, 0.3451988 ],
       [0.36795976, 0.60119013, 0.03085011],
       [0.53594412, 0.02377894, 0.44027694],
       [0.31548513, 0.36288743, 0.32162744],
       [0.54940435, 0.28345464, 0.16714101],
       [0.02470614, 0.26705735, 0.70823652],
       [0.20294435, 0.63061   , 0.16644565],
       [0.52931405, 0.11922617, 0.35145979],
       [0.42886918, 0.29170424, 0.27942658],
       [0.44892045, 0.14038906, 0.4106905 ],
       [0.00550195, 0.21114395, 0.7833541 ],
       [0.0396458 , 0.33534023, 0.62501398],
       [0.54751011, 0.24700572, 0.20548417],
       [0.4775605 , 0.21242959, 0.31000991],
       [0.07433192, 0.85562996, 0.07003813],
       [0.5491294 , 0.09780392, 0.35306668],
       [0.55690415, 0.07797629, 0.36511956],
       [0.56203683, 0.37658527, 0.0613779 ],
       [0.51508218, 0.47076881, 0.01414902],
       [0.

In [82]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [83]:
confusion_matrix(y_test, y_pred)

array([[59,  5,  4],
       [ 7, 52, 12],
       [22,  8, 31]])

In [84]:
accuracy_score(y_test, y_pred)

0.71

In [85]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.67      0.87      0.76        68\n           1       0.80      0.73      0.76        71\n           2       0.66      0.51      0.57        61\n\n    accuracy                           0.71       200\n   macro avg       0.71      0.70      0.70       200\nweighted avg       0.71      0.71      0.70       200\n'